### ISSUE TITLE
[Doc] What AWS permissions are required for running this SQS connector

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar-io-sqs#124]
# Request doc changes

Please answer the following questions before submitting your doc issue. Thanks!

## What issue do you find in the docs (for example, something inaccurate, incomplete, missing, or hard to use/understand/find, etc)?

Missing. There is no documentation about the required AWS permissions.

## What is your suggestion?

We need clear documentation on the required AWS permissions.

**Comment by nlu90** [comment]
@freeznet could you help take a look?

**Comment by sijie** [comment]
- SQS Source Connector:
	sqs:CreateQueue
	sqs:ChangeMessageVisibility
	sqs:GetQueueUrl
	sqs:GetQueueAttributes
	sqs:ReceiveMessage


- SQS Sink Connector:
	sqs:CreateQueue
	sqs:SendMessage

**Comment by Anonymitaet** [comment]
@freeznet will provide tech inputs this week and I'll draft and review based on that

**Comment by freeznet** [comment]
I have drafted a doc https://docs.google.com/document/d/1m62bajYopZ_LrFl82mgYqU1m6MkxF5NyU71nhh1Ewsc/edit?usp=sharing, PTAL.

**Comment by Anonymitaet** [comment]
@Huanli-Meng FYI: Rui provided some inputs here
