### ISSUE TITLE
[Release workflow] change specific version to variable 

### ISSUE THREAD

**Issue by Anonymitaet** [streamnative/pulsar-io-sqs#32]
I've created a branch `hub-test` and changed specified version `2.7.0` to `{{connector:version}}` in both [`sqs-sink.md`](https://github.com/streamnative/pulsar-io-sqs/blob/hub-test/docs/sqs-sink.md) and [`sqs-source.md`](https://github.com/streamnative/pulsar-io-sqs/blob/hub-test/docs/sqs-source.md).

@timmyyuan will update the release workflow. Could u please go ahead w/ your task? Thanks

**Comment by Anonymitaet** [comment]
@timmyyuan may I know the status of this work? Thanks.

**Comment by timmyyuan** [comment]
@Anonymitaet This work is expected to be completed next week, after we migrate our projects to Maven Central.
